### ISSUE TITLE
Reduce dependencies vulnerabilities

### ISSUE THREAD

**Issue by bergmannlucas** [bergmannlucas/btc-converter-cli#1]
Today the project dependencies contains 446 vulnerabilities. We wanna reduce that number and add the vulnerabilities badge on README.

![image](https://user-images.githubusercontent.com/18709255/66170694-9a600400-e61b-11e9-84c1-48b681402f95.png)

**Comment by joaaomanooel** [comment]
Hey Bergamot, can I get assigned?

**Comment by bergmannlucas** [comment]
Sure!
